spring.application.name=reservas

# 1. URL: En Docker usa la de red interna, en el IDE usa la variable SPRING_BD_LOCAL_IDE
spring.datasource.url=${SPRING_DATASOURCE_URL:${SPRING_BD_LOCAL_IDE}}

# 2. Credenciales: Si existe la de Docker la usa, sino cae en la de tu IDE local
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}

spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / Hibernate
# ============================================
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:${JPA_DDL_AUTO}}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Evita alertas con el nuevo dialecto de Hibernate
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Puerto: Usa el de Docker o cae al 8080 por defecto
server.port=${SERVER_PORT:8080}